### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VinnieV** [manstis/test#1]
Hey Manstis,

Maybe kinda strange to ask my question via this medium but I didn't find any other way.
I have a small question about Drools. I noticed that you are actively helping with source code.

I am currently doing a security source code review of Drools and noticed something strange.
A lot of classes have these both functions: **readExternal and writeExternal.**
But I can't seem to find any usage of this functions. **Are they used or is it deprecated?**

It seems like this function is accepting a object parameter en deserialises that parameter. As we know that can be dangerous if this value is originating from the user. 

Sorry for bothering you, hopefully you can help.
(any issues found during the analysis will be communicated, so its also good for the drools project)

Thanks!
Kind regards,
Vinnie

**Comment by manstis** [comment]
Can you please post your question to https://groups.google.com/forum/#!forum/drools-development

We don't tend to respond to Git issues; in particular issues posted against unrelated Git repositories.

**Comment by VinnieV** [comment]
Ok thanks, will do that.
